### ISSUE TITLE
Several minor bugs

### ISSUE THREAD

**Issue by raven2cz** [WebCoder49/code-input#12]
First, NICE work! Thanks for this trick.

I tested your release and found several problems (maybe bugs). This is my tested element:
```html
<code-input id="httpHeadersCodeInput" style="font-size: large; resize: vertical; overflow: auto; height: 400px; width: 100%;"
                          lang="HTTP" placeholder="Type HTTP HEADERS here" template="syntax-highlighted" onchange="httpHeadersOnChange(this.value);"
                          value="Accept-Charset: utf-8"</code-input>
```

There are a list of them which I found:
* `placeholder` is not shown. I tried to remove `value` param, but the placeholder is not shown in text area.
* function `onchange` is not called, no action for this function. I tried to test `oninput` which works. Maybe change your documentation guide?
* In some environments, like `bootstrap`, the triangle for resizing of area is outside of rendered code rectangle. In addition, it seems that much more space is defined outside. Maybe some wrong calculation between text area and code area. Screenshot attached
![image](https://user-images.githubusercontent.com/20504243/178208169-2d54b8c6-49ec-49a6-b6ea-737bbc266870.png)
* Default font is very large, around extra-large or higher. It is not common approach, I have to use `font-size: large` for standard font size. This is a strange behavior.

**Comment by WebCoder49** [comment]
Thank you for mentioning these - I will start to fix them now.

**Comment by WebCoder49** [comment]
Does this work with bootstrap for you?
https://github.com/WebCoder49/code-input/commit/45a8ed9d9019c850fa97444c1d81b1ce7dbdaebe

**Comment by raven2cz** [comment]
> Does this work with bootstrap for you? [45a8ed9](https://github.com/WebCoder49/code-input/commit/45a8ed9d9019c850fa97444c1d81b1ce7dbdaebe)

Works! Thanks for all corrections. Can you release it and provide it by cdn.jsdelivr.net? Thx!

**Comment by WebCoder49** [comment]
Yes; [this is release 1.1.1](https://github.com/WebCoder49/code-input/releases/tag/v1.1.1):
```html
<script src="https://cdn.jsdelivr.net/gh/WebCoder49/code-input@1.1/code-input.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/WebCoder49/code-input@1.1/code-input.css">
```
