### ISSUE TITLE
Cursor not precise

### ISSUE THREAD

**Issue by ahmadi330040** [WebCoder49/code-input#14]
Previously I tried it on plain html with no problem, but when I implemented it on a node js pug project, the cursor was not precise, is there a solution?

**Comment by WebCoder49** [comment]
Please could you take two photos of the code-input, one with no text highlighted, and one with everything highlighted, so I can see if this is a problem with incompatible CSS or HTML?

**Comment by ahmadi330040** [comment]
![image](https://user-images.githubusercontent.com/67589784/180390226-ccce1239-3657-4a92-b178-e75e00ccce60.png)
as an example of this photo, I wrote the same 2 sentences, the upper one is the <pre> tag, then the lower one I highlighted the <textarea> tag

**Comment by ahmadi330040** [comment]
btw i'am also using css bootstrap and css from atlantis template

**Comment by ahmadi330040** [comment]
i have found the solution, it's because letter-spacing follow css bootstrap agent, so i redefined "letter-spacing: inherit;", thanks before 😁
