### ISSUE TITLE
support other languages/syntax

### ISSUE THREAD

**Issue by jaygray0919** [WebCoder49/code-input#18]
I would like to customize your code to support other languages.
One is XML and variants such as RDF.
A second is JSON and JSON-LD.
A third is Turtle used to define SPARQL queries as used on Wikidata.
  Example: https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service/queries
Would you identify the resources I need to modify to support the above?
Thanks in advance.
/jay gray

**Comment by WebCoder49** [comment]
Dear Jay Gray,
This support would be more in the realm of the syntax highlighter used. Prism.js appears to support more of these than highlight.js (https://prismjs.com/#supported-languages):
* `xml` (RDF not supported)
* `json` (JSON-LD not supported)
* `turtle` or `sparql`
* If you want to add the language yourself, [this may be useful](https://prismjs.com/extending.html#language-definitions).

I would suggest adding the indentation plugin as well as any others you want as these languages are quite indentation-heavy.
Demo: https://codepen.io/WebCoder49/pen/BamoWoa

**Comment by jaygray0919** [comment]
Thank you for the CodePen. I can use this short term.
My plan is to run your code in an iFrame juxtaposed with a discussion about target code.
Previously, we generated an SVG using Carbon: https://carbon.now.sh/
Your solution is superior.
Also, am plan to use your code in a form, where a button triggers the formatted text in the form.
For example, put a button in the form that triggers the SPARQL query as displayed.
The Turtle syntax is basically the same as SPARQL, so we're good there.
RDF is XML with namespace declarations, so we can adapt the XML example
Thanks again for this product.
/jay
