### ISSUE TITLE
Handlebars support

### ISSUE THREAD

**Issue by echonax** [WebCoder49/code-input#2]
Hello,
First of all thanks for creating this project, great stuff.

I tried to change the lang to `handlebars` but I assume it doesn't work out-of-the-box. Is there a way to register this? Prism and highlight.js do have support for handlebars

Thanks in advance

**Comment by WebCoder49** [comment]
@echonax , this should support all the languages registered as Prism/highlight.js are allowed to highlight however they want using their function in the result. However, the language may not have been imported. Prism has an **[autoloader plugin](https://prismjs.com/#basic-usage-cdn)** for the CDN which seems to work in the demo.

**Comment by echonax** [comment]
You're right! I must have been looking at the other example. Works in this one: https://codepen.io/WebCoder49/details/jOypJOx
Thank you very much!
