### ISSUE TITLE
Custom Template highlight function with no arguments

### ISSUE THREAD

**Issue by drewbitt** [WebCoder49/code-input#20]
In the README, the documentation for the custom highlight function is:

```js
codeInput.registerTemplate("syntax-highlighted", codeInput.templates.custom(
  function(result_element) { /* Highlight function - with `pre code` code element */
    /* Highlight code in result_element - code is already escaped so it doesn't become HTML */
  },
```

However the actual code of the function is:

![image](https://user-images.githubusercontent.com/26885897/211213607-26b5729e-e392-449c-a33e-cb34fa999b1f.png)

![image](https://user-images.githubusercontent.com/26885897/211213995-180d7e54-25a6-478d-9d58-27aa203f13c1.png)

The highlight function does not take any arguments and therefore cannot take `result_element`. Therefore I do not think the custom function is usable at all with no arguments available - let me know though how to use it otherwise. It lacks documentation in the article or in the repo.

**Comment by WebCoder49** [comment]
It appears that you've fixed it; thank you for taking action. I will change the misleading line of code as soon as possible.
