### ISSUE TITLE
Form Data with Code-Input text box

### ISSUE THREAD

**Issue by Normanras** [WebCoder49/code-input#23]
I just implemented this today into my Flask App and I absolutely love it! Great job with this plugin. Also, way easier than the css-tricks blog post. Great job on all of this! 

The issue I'm having is that I want the text in the `code-input` box to be picked up by a form submit button. But the Form doesn't seem to notice it. The page loads without issue - formatting and everything - but it doesn't get passed within the form when you click submit. 

I'm considering adding an `onclick` script to copy the value of the box to a `textarea` box and then pass it into the form, but I'm not sure if I'm misunderstanding something about the plugin that would make it easier. 

Thanks again!

**Comment by WebCoder49** [comment]
It's certainly true that this plugin should work out-of-the-box with HTML forms; I will address this issue as soon as possible.

**Comment by Normanras** [comment]
Interesting. Okay, that makes me feel better cause I've been reformatting the app to see if I can figure out some workarounds. 

I did get the js script to pull from `code-input` successfully, so it's not a terrible workaround. But I'll also say that when I inspect the working page, the `textarea` element under `code-input` has no `id` or `name`, which is how Flask pulls the data into python. Not sure if the `name` I give the `code-input` element goes to the child or not, but that was something that stood out to me.

**Comment by WebCoder49** [comment]
In the latest version, if the code-input element is created with a `name` attribute, it does appear to work as expected. For example, this will search Google with any JS code in MS Edge, Google Chrome and Firefox.
![image](https://user-images.githubusercontent.com/69071853/225248995-5fcba9c0-df71-44a7-85de-b58368585b80.png)
However, I do notice that if the `name` attribute is changed later, the element does not appear to update. I will work on that in a new branch now. I would suggest you use `document.getElementById("id").querySelector("textarea")` if you want to get the textarea by code-input element ID (or you can use `document.getElementById("id").value` for the text value), as syncing the `value` like the `name` attribute will probably cause unexpected actions in other code using code-input.

**Comment by WebCoder49** [comment]
The above pull request synchronises the `name` attribute.

**Comment by WebCoder49** [comment]
I've tested it and added it to the latest release. Please ensure you are using v1.2.2, and let me know if it works or if more changes need to be made.

**Comment by Normanras** [comment]
And I can confirm that it works! Really appreciate your help and turnaround on this, this has been a huge help and cuts out a bunch of extra functionality on my end. Thanks again! 

![image](https://user-images.githubusercontent.com/44226464/225343161-c3b2f368-33c0-4d56-bfb9-f3b59d944202.png)
