### ISSUE TITLE
Problem & Fix for tab character...

### ISSUE THREAD

**Issue by AzzaAzza69** [WebCoder49/code-input#26]
As you manipulate the string via code in the check_tab function, the ability to undo (ctrl+z) is lost...can I suggest instead:

function check_tab(element, event) {
  let code = element.value;
  if(event.key == "Tab") {
    /* Tab key pressed */
    event.preventDefault(); // stop normal
    document.execCommand('insertText', false, "\t");
    update(element.value); // Update text to include indent
  }
}

**Comment by WebCoder49** [comment]
Thank you for this; it look very useful.
I am afraid that I am very busy at the moment so it is unlikely I will be able to address this until Monday 27/03.

**Comment by mitchcapper** [comment]
for master changing
https://github.com/WebCoder49/code-input/blob/8279834eebc3e7bff3db0347512859c2f0aa6d7e/plugins/indent.js#L29-L37
to 
`document.execCommand('insertText', false, "\t");` 
would seem to replicate @AzzaAzza69 fix.

**Comment by WebCoder49** [comment]
I have released this in version 1.2.4.
