### ISSUE TITLE
Problem & fix for subsequent lines overwriting previous...

### ISSUE THREAD

**Issue by AzzaAzza69** [WebCoder49/code-input#27]
You can see this happen to the "p" on your animated gif here:
https://i0.wp.com/css-tricks.com/wp-content/uploads/2021/06/syntax-highlighted-textarea.gif
and also if you try this example:
```
<span></span>
<test>   <-- this line overwrites the bottom of the p in "span" of the above line...
```
where by the descender part of the "p" is overwritten by the next line...

Proposed fix:
as the lineheight is set to 1.5 via:
`	code[class*="language-"], pre[class*="language-"] {
`
it should be also set to 1.5 on (and not 20pt) here:
`	#editing, #highlighting, #highlighting * {
`

**Comment by WebCoder49** [comment]
Thank you for this.
I am afraid that I am unlikely to be able to address it until Monday 27/03 as I am very busy at the moment.

**Comment by WebCoder49** [comment]
I am sorry that I couldn't address this for a while as I was busier as I had anticipated. I have now fixed this bug in both the CodePen and the library.
