### ISSUE TITLE
Errors in the console

### ISSUE THREAD

**Issue by kvnloughead** [WebCoder49/code-input#3]
I'm new to web components, so forgive me if it's user error. But I've been getting errors (image at the bottom) in the console stemming from the `attributeChangedCallback`. Screenshot shows it coming from a local file, but it's the same from the cdn. I've resolved it by wrapping the `switch` block in an `if` block:

```javascript
  if (this.isConnected) {
    switch (name) {
     // snip
  }
```

Regarding usage, I have this in the head of index.html

```html
<script src="./src/vendor/code-input.js"></script>
<script>
    codeInput.registerTemplate(
      'code-input',
      codeInput.templates.prism(Prism)
   );
</script>
```

and then I have code-input slotted into my-app

```html
<body>
    <my-app>
      <code-input
        slot="code-input"
        lang="Markdown"
        placeholder="Enter some markdown"
      >
      </code-input>
    </my-app>
  </body>
```

The errors also go away when remove the `lang` and `placeholder` attributes from `code-input`.

![image](https://user-images.githubusercontent.com/37159177/166344930-748dd07c-b5b5-4d35-ad34-a0bc199187db.png)

Nice component though, and nice article accompanying it.

**Comment by WebCoder49** [comment]
Thank you for pointing out the fix to this bug and the `isConnected` flag. I have added your edits to the repository. If you have any more suggestions or contributions, please feel free to create another issue.
<sub>Sorry for the delay as I have been rather busy recently. </sub>
