### ISSUE TITLE
\u0096 character causes misalignment

### ISSUE THREAD

**Issue by SArpnt** [WebCoder49/code-input#32]
github seems to be replacing the character "", the character code is \u0096;
on firefox, it renders in a textarea/input but not in regular elements, and i was unable to find any css style that controls this.
this probably also affects other characters
some other unicode characters like \ue8fb "" seem to work fine

i think this box display is part of the browser, not any particular font.

it is NOT the same width as the replacement character (�), white square (□), white vertical rectangle (▯), and combining enclosing square (⃞) doesn't have kerning, but also visually isn't the same width

one solution could be to actually render all the text in various styled input elements, but that would probably have very bad performance and be a nightmare for styling.

another possible solution could be to choose a character that always renders (test various browsers and platforms), use that a replacement, hide that text, then overlay something on top of it like the replacement character or 5 svgs or something. maybe the other character wouldn't be needed and you could just use an svg if it works the same in all fonts, browsers, and operating systems.

**Comment by WebCoder49** [comment]
Thank you for letting me know about this. When I have time, I will try to implement a plugin that uses SVG/CSS/equivalent to render special characters as escapes.

**Comment by WebCoder49** [comment]
I have started making a plugin ([branch `display-special-chars`](https://github.com/WebCoder49/code-input/tree/display-special-chars)) which may be able to fix this, but it doesn't work in Firefox as although the font is monospace the special character replacement in the textarea is wider than other characters. If you only need a few special characters to be rendered, using the plugin (once I/you have fixed the other bugs in it - I've not got much time now), you may be able to create a CSS rule to make this specific character replacement wider (untested):
```css
.code-input_special-char[top="00"][bottom="96"] {
    width: /* Found experimentally */;
}
```


Here's an image of it in Chromium (Edge):
![image](https://user-images.githubusercontent.com/69071853/231390707-d2324666-abae-44f4-9b87-d552f1cac2df.png)

The "00FF" element in `pre code` is styled by CSS, and has this HTML:
```html
<span class="code-input_special-char" data-top="00" data-bottom="FF"> </span>
```

**Comment by WebCoder49** [comment]
What do you think of this display for the control characters? I have made them larger and increased the line-height so the numbers are more visible, removed the first two numbers as they will always be "00" for ASCII characters, and made an algorithm that chooses a background colour based on the number.

![image](https://user-images.githubusercontent.com/69071853/231542098-72f5a6fd-9e30-4b69-9df0-95e97a7e1c4e.png)

**Comment by WebCoder49** [comment]
I have changed it to make characters with similar numbers look very different. Do you prefer this or an algorithm where similar numbers have similar colours?
![image](https://user-images.githubusercontent.com/69071853/231547809-5b631aab-708d-47f0-a308-1a1e1c1d93bf.png)

**Comment by WebCoder49** [comment]
I've got something that works well with Chromium now using the above, but it still estimates the width wrong in Firefox. I have tried using an HTML5-canvas-based width-getter, but it is giving unexpected results. Please let me know if you have any suggestions; otherwise, I will make some code to check whether the browser is Firefox and the character is unprintable, so it only changes the width then.

**Comment by WebCoder49** [comment]
Please don't use this in production yet - I have realised there are still some other bugs I need to fix.

**Comment by WebCoder49** [comment]
I have now fixed the above bugs and will release the plugin soon.

Chromium|Firefox
---|---
![image](https://user-images.githubusercontent.com/69071853/231973620-d4e2c31d-e7d2-4cfe-8d42-0999c682c245.png)|![image](https://user-images.githubusercontent.com/69071853/231974028-d2fafbe5-687c-416f-9b51-ff79cafd557d.png)

**Comment by SArpnt** [comment]
i think the line height is just way too large. these characters wouldn't randomly show up in english text with sentences on single lines, in my case it was on a website where code golfing shenanigans are common:
```js
r=11e3,s=int(t/r+1)%32,b='ćóóóćÎÎÎÎÃÃÃÃÃÃÎ°°°°¦¦¦¦'.charCodeAt(s)/300*t%512,160/3*(sin(t%r/(t%r/100+8))+1)*(s%2+.6*!(s%16))+b%(400+128*sin(b/(21+sin(t/r))))%256/3+(.999*(0xDBC97749&2**s?2*b:b)%128>64+15*sin(t/1e4)?64-t/r%1*32:0)
```
i feel like it would be confusing to randomly see a block 4 characters tall in the middle of text, and in many cases make it more difficult to read. i prefer the way firefox displays it, with a box and bitmap font. the font is only 16 tiny characters, which could each go in a bmp file (a png would probably be larger considering how small the image is)

**Comment by WebCoder49** [comment]
Thank you for your suggestions. I am happy to work on this when I have time; it shouldn't be too difficult to transfer it as it is mostly a CSS issue. I have created most of the JS for this.

**Comment by WebCoder49** [comment]
Please could you just confirm that you want a style like this image, but with a simpler bitmap font?

![image](https://user-images.githubusercontent.com/69071853/232197335-76e9ba61-aa48-4693-816d-76b35dae50b8.png)

Thank you for your continued suggestions.

**Comment by SArpnt** [comment]
yes, i think something like that would work well. it's the best way i can think of doing it at least since other options don't really work well with the flow of the text.

**Comment by WebCoder49** [comment]
I have this as an idea for the special character display (but with a border); it supports inheriting the font color using CSS. Once I have implemented this fully, the plugin should be ready for release.
![image](https://user-images.githubusercontent.com/69071853/232280486-8d96065e-6199-4e09-8c04-b00e2ef0c35c.png)

**Comment by WebCoder49** [comment]
Dear @SArpnt ,
I am afraid that I am very busy at the moment so will not be able to implement this until next weekend at the earliest. I have pushed the work-in-progress CSS code to the branch so you can fork and submit a pull request if you want. Please let me know if you're doing so, so we do not both do the same thing to the same code at the same time.

**Comment by SArpnt** [comment]
i'm not in a hurry, you don't need to work on this if you're busy with other stuff, i have other things i can do and i could probably contribute if this is something i really want to work on at some point soon. i really do appreciate the work you're putting into it though, it's a nice change of pace from other libraries i've tried to use, thanks for that

**Comment by SArpnt** [comment]
some more unicode stuff i found to watch for:
these two characters put together (dbff, dcff) (� �) when put together represent a new codepoint (10fcff) (􏳿), which shows in a wider box, with 3 columns, 2 rows. i'm not sure it's actually valid to have them seperate. copying and pasting them doesn't work because it's probably not valid text and just utf16 nonsense. many other characters do the same thing.

these large characters come from this combination of codepoints: https://en.wikipedia.org/wiki/UTF-16#Code_points_from_U+010000_to_U+10FFFF

10ffff is the largest unicode codepoint, so a larger box is never needed.

i looked over the [planes](https://en.wikipedia.org/wiki/Plane_(Unicode)#Supplementary_Multilingual_Plane) and i don't see anything that looks like it might render in a textarea as a box but not in a regular element, i tested tags and variation selectors supplement

**Comment by WebCoder49** [comment]
Thank you for looking at this. It is helpful that there are no 4-byte Unicode characters.

**Comment by WebCoder49** [comment]
What do you think of something like this?
![image](https://user-images.githubusercontent.com/69071853/235341453-e8865ced-3289-48af-8f68-5ded73941288.png)

**Comment by WebCoder49** [comment]
Sorry for the delay - I'm slightly stuck with the Firefox bug, but I have the above working with Chromium with the correct hex codes. I will wait for a response on StackOverflow about the Firefox bug; please share ythis link to anybody you know who could help.
https://stackoverflow.com/questions/76145682/how-do-i-find-the-width-of-a-character-in-a-textarea-in-javascript

**Comment by WebCoder49** [comment]
![image](https://user-images.githubusercontent.com/69071853/236608385-dd694b59-27e6-42a5-82e3-ccbe8800dce1.png)
![image](https://user-images.githubusercontent.com/69071853/236608414-64416d8d-b2dd-4219-96af-607168d84731.png)
I have completed this plugin now and will merge it to a new release.
