### ISSUE TITLE
Noticed possible bug in source...

### ISSUE THREAD

**Issue by AzzaAzza69** [WebCoder49/code-input#41]
````
...line 79...
            if(this.querySelector("textarea").value != text) this.queryS
            this.querySelector("textarea").value = text;  
...
````
I think the "**this.queryS**" is a typo as I can't see any mention of it anywhere else!

**Comment by WebCoder49** [comment]
Yes, it is; It's weird as I don't remember writing that. I've fixed that line with [a quick patch](https://github.com/WebCoder49/code-input/releases/tag/v1.4.1).
