### ISSUE TITLE
<code-input> can't be used before on the page before the template is registered.

### ISSUE THREAD

**Issue by SquirrelFall** [WebCoder49/code-input#6]
I attempted to create a codepen that used code-input. I included Prismjs and code-input with the External Scripts option in settings, rather than including them in the HTML like your demo. 
I placed the registerTemplate call in the JS editor pane. Unfortunately Codepen places your custom javascript as the last <script> tag. The result is that the code-input object is declared, then code-input.js registers the custom element, and the browser calls connectedCallback(). However, this.template ends up undefined because registerTemplate() has not been called yet.

Perhaps the highlight library could be another code-input attribute such as `library="prism"`? For example:
```
<code-input  library="prism" lang="JavaScript" placeholder="Enter some JS!" value=""></code-input>
```

I tried adding this option in `connectedCallBack()` and it seemed to solve the issue, of course it does not help for custom highlight.
 

```
            // Added to document
           this.template = codeInput.usedTemplates[this.getAttribute("template") || codeInput.defaultTemplate];
          if (this.template == null) {
            if (this.getAttribute("library")!==null) {
                switch(this.getAttribute("library")) {
                  case "prism":
                    codeInput.registerTemplate("code-input",codeInput.templates.prism(Prism));
                }
              this.template = codeInput.usedTemplates[this.getAttribute("template") || codeInput.defaultTemplate];
            }
          }
```

**Comment by WebCoder49** [comment]
This should hopefully solve the issue.
