### ISSUE TITLE
Repeating inputing newline character makes cursor exceeds the bottom range.

### ISSUE THREAD

**Issue by Ziqi-Yang** [WebCoder49/code-input#61]
demo:
https://codepen.io/ziqi-yang/pen/rNPNgeO

used framework: code-input with prism.js 
  code input enabled plugins: Indent
  prism.js enabled plugins: prism-autoloader prism-line-numbers

description:
In chromium (my version: Chromium 118.0.5993.88 Arch Linux), when you hit "Enter" repeatedly, you can see the cursor exceed the bottom range of code-input, then you need to scroll to the end or input some characters other than "Enter". In firefox developer version 119.0b9, the behavior seems fine.

caused reason: 
`font-size: 20px;` style for `code-input`

**Comment by WebCoder49** [comment]
Thanks for this very detailed description - I should be able to implement and test the fix by this weekend. It's an amazing idea to put a CodePen demo!

**Comment by Ziqi-Yang** [comment]
Thank you for your invitation <3 ! However, I'm not every familiar with both of the two libraries (also front end XD). It can be predicted that tons of times may be spent into fix it and I just haven't that time right now. Thank you.

**Comment by WebCoder49** [comment]
@Ziqi-Yang, thank you again for your contribution; it has now been [released in version 2.1.0](https://github.com/WebCoder49/code-input/releases/tag/v2.1.0). You can use the code you already have but please change any instances of `2.0` to `2.1`.

Have a great week!

**Comment by Ziqi-Yang** [comment]
Thanks, you too!
