### ISSUE TITLE
problem and possible solution for searching the page (ctrl-F)

### ISSUE THREAD

**Issue by andrelsm** [WebCoder49/code-input#65]
**hello**, WebCoder49!

First of all, thank you very much for this work. I'm implementing an ultra lightweight WebIDE, trying to use the most of the functionality already available in the browser, avoiding  tons of client-side scripts... I'm quite satisfied with CodeInput, I intend to adopt it as the code editing solution in my project.

I noticed that the search on the page (ctrl-F) presents duplicate terms (sometimes losing scroll synchronization), because the browser scans the content of the textarea element and also of the beautifier pre element. I managed to get around this using the following approach in my custom highlighter:

**ulight.js:**

```
// append
if (token) {
  pre.appendChild(node = document.createElement('span'));
  if (token_class) node.className = token_class;
  node.dataset.token = token;
}
```
**ulight.css:**

```
.ulight [data-token]:before {
  content: attr(data-token);
}
```

hope it helps
my best regards
andrelsm@Brazil

CodeInput / ulight in action:
![ulight codeInput](https://github.com/WebCoder49/code-input/assets/1190616/44669f3b-b88e-4218-95ab-69c146a4da6e)

**Comment by WebCoder49** [comment]
Dear andrelsm,

Thank you very much for your comments and for your solution! I am quite busy now but as soon as I have time will implement this code as a plugin that works with any highlighter, or, better still, find a non-syntax-highlighting-algorithm-invasive solution for the main part of the library.

**Comment by andrelsm** [comment]
> Dear André Luís,
> 
> Thank you very much for your comments and for your solution! I am quite busy now but as soon as I have time will implement this code as a plugin that works with any highlighter, or, better still, find a non-syntax-highlighting-algorithm-invasive solution for the main part of the library.

hello again, friend,

I'm not sure if such a bugfix should be the responsibility of a plugin (optionally activated)... But I completely agree with looking for an "agnostic" solution, which can do the job for any highlighter of the user's choice.

Maybe having an extra step, post-highlighting, turning "stealthy" the elements generated in the pre-container? As in the following example?

```
function stealthy(s) {
  var token;
  
  for (var i = 0; i < s.childNodes.length; i++) {
    token = s.childNodes[i].textContent;
  
    if (s.childNodes[i].nodeType == 3) {
      s.replaceChild(document.createElement('span'), s.childNodes[i]);
    }
    
    s.childNodes[i].dataset.token = token;
    s.childNodes[i].innerText = '';
  }
}
```

PS: In fact, this function should check/convert all child nodes recursively...
PS: I wonder what the negative impact of this approach will be on overall performance...
PS: CSS could have a 'user-search: none' property, similar to 'user-select: none'...

regards
[ ] andrelsm

**Comment by WebCoder49** [comment]
Dear André Luís,

Yes, I think that's definitely a good idea. I could add an optional true/false parameter alongside the existing ones when creating the template, and make it true for highlight.js and Prism.js, while allowing custom highlighters to implement 'stealthy elements' themselves (which I guess would be more efficient than recursing over all nodes afterwards).

Thank you so much for the code, and please let me know what you think of the suggestion.

Regards, WebCoder49.

**Comment by andrelsm** [comment]
hi, friend,

It seems like a good way to add another flag controlling this extra post-highlighting transformation step, because it gives the opportunity to document the feature for developers of custom highlighters... Another option would be to check if the first child node of the pre already contains the dataset.token attribute, eliminating the need for scanning. That would be a nice approach too... But in that case, how can we make developers aware of this?

**Comment by WebCoder49** [comment]
I've got a general fix for this using your suggestion but it only works on some browsers:
|Browser|Works?|
|---|---|
|Microsoft Edge Desktop 119.0.2151.97|✅|
|Google Chrome Desktop 120.0.6099.71|✅|
|Mozilla Firefox Desktop 120.0.0.1|❌|

**Comment by WebCoder49** [comment]
The only Firefox-compatible fix seems to be converting the result element to an image, which is processor-intensive, needs a new dependency and generally gives low-resolution results.  I will open a new issue waiting for a Firefox fix, and meanwhile will merge this Chromium fix.

**Comment by WebCoder49** [comment]
For now, I'll submit the Chromium fix and hope we can get it working on Firefox in a future release. At least we're part of the way there.

**Comment by andrelsm** [comment]
Amazing!

Indeed, despite showing a duplicated total sum in the search bar, Firefox shows only "non inert" content while we scan results. It prevents loss of scroll synch. It is an acceptable solution. Unfortunately, Chromium does not interpret this attribute in the same way... (Specification x Specificities hell!) 




PS: This is the principle that brought me to CodeInput: making the most of the functionality already available...

 

[ ] André Luís

 
 

Sent: Friday, December 08, 2023 at 7:30 AM
