### ISSUE TITLE
Plugin to auto-close brackets and indent after brackets open

### ISSUE THREAD

**Issue by WebCoder49** [WebCoder49/code-input#67]
It might be nice having a plugin to auto-create closing brackets `()`,`[]`,`{}`,`<>` but still allow the user to type them, and adding a flag to the Indent plugin allowing auto-indentation when there is an opening bracket and a new line is created. This is an important part of my workflow in VSCode and is supported by both CodeMirror and Monaco, so I think it would be useful here.

![AutoCreationBrackets](https://github.com/WebCoder49/code-input/assets/69071853/a4781089-f459-4a60-89d7-681e99be0242)

**Comment by WebCoder49** [comment]
[@andrelsm, @vcdomith, @Ziqi-Yang, @vanowm, @Kerdek, @AzzaAzza69, @SArpnt, @dfoverdx, @KaiWilke, @mitchcapper]
Dear All,

As the 10 latest contributors to `code-input`, I was wondering whether you could comment on this addition - it would really help me gauge its popularity/need/lack thereof. Sorry for @ mentioning 10 people at once - please let me know if this is not the etiquette.

Regards, WebCoder49.

**Comment by Ziqi-Yang** [comment]
I think it would be useful and I'm happy to see this feature! I think it would be lightweight, which suits this library.

**Comment by mitchcapper** [comment]
Personal I disable this in any editor I can.  Not sure if it is just because of programming for so long, or the fact that if I am editing in a remote CLI that doesn't have it or a quick open in notepad so different muscle memory would seem bad.  I generally find the bracket 'help' gets in my way more often than not.

Of course this feature is actually quite popular, and that is why many editors have it on by default so for the bulk of the public and users using this as an option probably a positive addition!

**Comment by KaiWilke** [comment]
Already implemented this functionality in my HTML editor. Its handy and was very easy to implement.

Cheers, Kai

**Comment by WebCoder49** [comment]
@KaiWilke if you don't mind and the license allows it, please could you put your code here as a GitHub Gist link, or in a pull request if jt is in plugin format?

**Comment by KaiWilke** [comment]
Hi @WebCoder49 ,

I extracted the relevant snippets and did a quick integration to your initial textarea/prism project...

https://css-tricks.com/creating-an-editable-textarea-that-supports-syntax-highlighted-code/

Simply add...

```
var editing=document.getElementById('editing');
editing.addEventListener('beforeinput',(e)=>{
	let d=e.data;
	if(d=='(')d='()';
	else if(d=='{')d='{}';
	else if(d=='[')d='[]';
	else return;
	e.preventDefault();
	document.execCommand('insertText',false,d);
	editing.selectionStart=editing.selectionEnd-=1
});
```

_**Note:** As we discussed in previous request, my personal textarea/prism solution is heavily based on 'execCommand'. So you probably need to replace this part with intensive coding's if you need to support full user-agent support._

Cheers, Kai

**Comment by KaiWilke** [comment]
Gosh, seems I've completely missed out the part to get an auto-intent new line if you hit 'enter' while being in between of the 'two matching braces'. 

Give me a minute, I'll recycle some parts of my 'enter key" emulation...

Cheers, Kai

**Comment by KaiWilke** [comment]
Here we go....

Reworked slightly the previous snippet and integrated auto-intent for enters between pairs of braces.

```
var editing=document.getElementById('editing');
editing.addEventListener('beforeinput',(evt)=>{
	let map='(){}[]<>',sels=editing.selectionStart,data;
	if(evt.inputType=='insertLineBreak') {
		let value=editing.value;
		if(map.indexOf(value.at(sels-1)+value.at(sels))%2!=0)return;
		let intent=value.slice(0,sels).split('\n').pop().split(/[^\t]/)[0].length;
		data='\n' + '\t'.repeat(intent+1) + '\n' + '\t'.repeat(intent);
		sels+=intent+2;
	} else {
		let pos=map.indexOf(evt.data);
		if(pos%2!=0)return;
		data=map.substr(pos,2);
		sels+=1;
	};
	evt.preventDefault();
	document.execCommand('insertText',false,data);
	editing.selectionStart=editing.selectionEnd=sels;
});
```

Result:

```
test (
	test [
		test {
			test <
				[cursor]
			>
		}
	]
)
```

@WebCoder49 My textarea/prism solution did only included auto-close of braces and a separate auto-intent on any new lines. Having this special auto-intent between a pair of braces is a small but very powerful addition! Thumbs up and many thanks for bringing up this idea... ;-)

Cheers, Kai

**Comment by SArpnt** [comment]
wouldn't normally comment on this but since i got pinged: i've pretty much only used this entire project as reference, i've completely redesigned it for the actual project i'm using it for to get rid of extra unnecessary code, i don't think i've ever used this as intended.

i don't have a use for this plugin, or most plugins really. i want something that behaves as close to a vanilla textarea as possible, only with some visual differences.

this does seem like a pretty basic feature though and about the same as all the other plugins, so i think this is still in scope for the project and would be nice to have for most people using it

---

on a seperate note, i suggest being careful about < and >, they aren't always brackets. something like this could happen:
```
let foo =
    (equation here) <
    (equation here)
```
there shouldn't be an extra indent on the second line here.

**Comment by KaiWilke** [comment]
Hi @WebCoder49,

below is the latest version fetched from my solution. 

The code below supports:

1.) Intercepted Enter sequence to:
a.) Auto-intent new line.
b.) Open and auto-intent braced code blocks
c.) Implement a fix for Chrome 'jump on enter' bug inside of textarea https://bugs.chromium.org/p/chromium/issues/detail?id=997266)
d.) Recalculate scrollTop and selectionStart/Ends to provide a smooth enter experience. It will adjust the viewable text area if the enter happens outside of the currently visible scolltop (at top or bottom).

2.) Intercept Tab sequence to:
a.) Support "insert Tab" on text area.
b.) Support "Shift+Tab" to delete leading Tabs or trailing Tabs if you are on the start of a given line.
c.) Support multi-line "insert Tab" or "Shift-Tab" sequences with automatic cleaning of empty lines and mixed tab+spaces usage inside of intents (the code below is written for 4char tab sequences).

3.) Intercept [, {, and ( sequence to:
a.) automatically insert closing braces.

4.) All key intercepts are handled by a execCommand function to fully support CRTL+Z undo buffer. 

```
function check_tab(ele,evt) {

	/*
	aI = ARRAYINPUTLINES
	aR = ARRAYRESULTLINES
	b = BRACES
	ch = CLIENTHEIGHT
	c = CODE
	cp = CURSORPOSHEIGHT
	ele = ELEMENT
	evt = EVTENT
	f = FOUNDNONEMPTYLINE
	i = FORLOOP
	it = INTENT
	k = KEY
	lh = LINEHEIGHT
	m= MODE
	bb = BRACEBLOCK
	st = SCROLLTOP
	s = SELECTIONSTART
	so = SELECTIONSTARTOFFSET
	sr = SELECTIONSTARTREMOVE
	e SELECTIONEND
	o OFFSET
	er SELECTIONENDREMOVE
	sk SHIFTKEY
	*/

	if(!['Enter','Tab','(','\{','\['].includes(evt.key))return;
	evt.preventDefault();
	let b=['()','{}','[]'],k=evt.key,sk=evt.shiftKey,s=ele.selectionStart,e=ele.selectionEnd,st=ele.scrollTop,c=ele.value,m='insertText';
	if(k=='Enter') {
		let it=c.slice(0,s).split('\n').pop().split(/[^\t]/)[0].length,bb=0,r;
		if(b.filter((x)=>x==c.at(s-1)+c.at(s))!='')r='\n'+'\t'.repeat(it+1)+'\n'+'\t'.repeat(it),bb=1;
		else r='\n'+'\t'.repeat(it);
		exC(m,r);
		let ch=ele.clientHeight,l=getComputedStyle(ele).lineHeight.slice(0,-2)*1,cp=(c.slice(0,s).split('\n').length+1+bb)*l;
		if(cp<st+l)st=cp-l*2;
		else if(cp>=st+ch)st=cp-ch+0.25;
		ele.scrollTop=st;
		ele.scrollLeft=0;
		ele.selectionStart=ele.selectionEnd=s+1+it+bb;
	} else if(k=='Tab') {
		if(s!=e) {
			let so=o=sr=er=f=0,aR=[],aI=c.split('\n'),it;
			for(let i=0;e>o;++i) {
				o+=aI[i].length+1;
				if(s>=o) {
					so=o;
					continue;
				};
				if((it=aI[i].split(/[^\t ]/)).length==1) {
					aR.push(''),++er;
					if(f<1)++sr;
					continue;
				} else {
					f=1,er=0,aI[i]=it[0].replace(/([ ]{4}|[ ]{1,3}\t)/g,'\t')+aI[i].substr(it[0].length);
					if(sk) {
						if(aI[i].startsWith('\t'))aR.push(aI[i].substr(1));
						else aR.push(aI[i]);
					} else aR.push('\t'+aI[i]);
				};
			};
			ele.selectionStart=so,ele.selectionEnd=o-1;
			r=aR.join('\n');
			exC(m,r);
			if(f)ele.selectionStart=so+sr,ele.selectionEnd=so+r.length+1-er,ele.scrollTop=st;
			return
		} else if(sk) {
			m='delete',so=c.slice(s-1,s);
			if((s==0||so=='\n')&&c.slice(s,s+1)=='\t')ele.selectionStart+=1;
			else if(so!='\t')return;
		};
		exC(m,'\t');
	} else if((r=b.filter((x)=>x[0]==k))!='') {
		exC(m,r);
		ele.selectionStart=ele.selectionEnd-=1;
	};
};
function exC(m,r) {
	document.execCommand(m,false,r);
};
```

Note: The function can be used natively in your original project. The only difference is probably that your solution uses a "Padding-Top" for the Textarea which makes it basically impossible to calculate a new scrollTop after you hit enter at the very bottom. You may want to increase the hardcoded "0.25" value to "6.25" to compensate your padding:10px based framing. 

License: Provided "as is", do whatever you want with this code as long as I'm still allowed to use my own code inside of my projects  ;-)

Cheers, Kai

**Comment by WebCoder49** [comment]
@KaiWilke thank you so much for this! However, I just implemented these features in the library using the plugin format - I didn't realise you were going to give me your code. I believe all of your points are implemented in the [`brackets-support`](https://github.com/WebCoder49/code-input/tree/brackets-support) branch. 

This branch adds to the `Indent` plugin to (optionally) **auto-indent and auto-unindent when the brackets indicate it's needed**, and also creates an `AutoCloseBrackets` plugin to automatically close brackets and also allow them to be typed normally, effectively overwriting the existing brackets. You can see what they allow below.

New Indent plugin (the brackets *caused* the indentation changes):
![IndentOnly](https://github.com/WebCoder49/code-input/assets/69071853/7dc3fe45-b4cd-438d-a82a-ceb5de236a4c)

New Indent plugin + Auto-Close Brackets plugin:
![Indent+AutoCloseBrackets](https://github.com/WebCoder49/code-input/assets/69071853/52e9e266-1abe-44b9-afbe-caa5667228e8)

**Comment by andrelsm** [comment]
@KaiWilke , thanks a lot. Added it as a plugin in my TextEditor class. It works weel, except for newlines at the bottom of the textarea.

PS: the Chrome jumps on [enter] really suck. Many thanks for the workaround.

**Comment by WebCoder49** [comment]
This has been implemented and should be released soon.
