### ISSUE TITLE
language autodetect

### ISSUE THREAD

**Issue by JaydenDev** [WebCoder49/code-input#7]
I'm writing a code editor in Electron, and I don't want the editor to be just one language. Auto-detect would be useful here.

**Comment by JaydenDev** [comment]
![image](https://user-images.githubusercontent.com/92550746/175116708-b684d645-1432-4fa8-858a-db73a821c7aa.png)

**Comment by WebCoder49** [comment]
Sorry for this. I will add support for no `lang` attribute ASAP.

**Comment by WebCoder49** [comment]
Does this work for you?

**Comment by JaydenDev** [comment]
works!

**Comment by JaydenDev** [comment]
Though it creates a text area and a code box instead of being combined into one.
![image](https://user-images.githubusercontent.com/92550746/175820808-69fe83a9-8fb9-4310-b196-189288fa2389.png)
