### ISSUE TITLE
textarea scrollbar is still visible

### ISSUE THREAD

**Issue by workingenius** [WebCoder49/code-input#8]
<img width="683" alt="截屏2022-07-03 上午10 47 49" src="https://user-images.githubusercontent.com/5379907/177022539-184f1bb4-b74f-4ae2-8d84-708c1db78d86.png">

Both the vertical and horizontal scrollbars are "doubled". Maybe the textarea scrollbar should be hided.

The screenshot is on chrome 101.0.4951.64, mac os.

**Comment by WebCoder49** [comment]
Sorry; I can't reproduce this error. Please could you give me more information, like a screenshot of the whole page or your HTML and CSS code for this part of the page?

**Comment by WebCoder49** [comment]
I'm afraid I can't fix this as I can't reproduce the error.
