### ISSUE TITLE
onKeyUp event support

### ISSUE THREAD

**Issue by arohman084** [WebCoder49/code-input#85]
is it possible to add blur to event listener ?  need blur event to toggle disabled button

**Comment by WebCoder49** [comment]
@arohman084 I am definitely happy to help. Do you mean you want to use the [`onblur` event listener on a `code-input` element](https://developer.mozilla.org/en-US/docs/Web/API/Element/blur_event), or use the [(code-input element)`.blur()` method](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/blur)? It sounds like you mean the first one.

I should definitely implement both of these, if they are not working already, but I can give you a workaround for the current version of `code-input` for which one you're having problems with.

**Comment by arohman084** [comment]
@WebCoder49 Ah man, I'm so sorry what I mean is onKeyup event listener, event trigger when user start typing on `code-input` element.

is it there already ? or you will add this event in the next future? thx, and sorry again for my mistake

**Comment by WebCoder49** [comment]
Thank you for clarifying so quickly, @arohman084 ! The `keyup` event does work, but if you want to see when the user starts entering any code into the `code-input` element, you might want to use the `input` event, that ignores arrow key presses that don't change the text, and is also triggered by non-keyboard text insertion like Right Click > Paste.

I have made a [demo of both of these (plus the `change` event, which shouldn't be used in this context), here](https://codepen.io/WebCoder49/pen/zYbejmW). Please let me know if you have any more questions - I'd be happy to help.
