### ISSUE TITLE
Setting code with line breaks from python flask

### ISSUE THREAD

**Issue by george-gca** [WebCoder49/code-input#87]
Thanks for the easy to use component!
I am currently facing issues to set up code contents from python flask code, more specifically with line breaks.

![image](https://github.com/WebCoder49/code-input/assets/31376482/49f0aa15-124a-43f1-80d2-a8413448790f)

I do it like this to get the code input contents from the python side:

```python3
code = request.form.get('markdown_code')
print(code)
print(repr(code))
```

which gives

```
aa
bb
'aa\r\nbb'
```

Now, when I try to get this same code and set it back to the component with:

```liquid
<code-input id="code" class="line-numbers code-display-wrapper" lang="Markdown"
name="markdown_code" placeholder="Write some markdown">{{ code }}</code-input>
```

It displays it in one single line, as:

![image](https://github.com/WebCoder49/code-input/assets/31376482/34c8e9da-c85e-4d0b-af04-58a40e18aaf2)

How can I properly display the same code again in the same component? I tried to use `code` as is, and even replace the characters `code.replace('\r\n', '\n')`, but it didn't work.

**Comment by WebCoder49** [comment]
Hello! Sorry for the late reply as I have been busy for quite a while. I will look at what might have caused that.

**Comment by WebCoder49** [comment]
I can't seem to reproduce this error with the minimal code below. Please could you try following these steps which might let you fix the problem?
1. Upgrade to code-input 2.2.1 (you may need to make some changes to your code [as outlined in the dropdown here](https://github.com/WebCoder49/code-input/releases/tag/v2.2.1))
2. Let me know more about how your server is transferring the code
3. Tell me the versions of code-input, Python and Flask you are using

I hope I can help, and thank you for opening an issue - have a good week and weekend.

## My Setup

Python 3.9, Flask 3.0.2

`app.py`
```python
from flask import Flask, render_template, request

app = Flask(__name__)

@app.route('/', methods=['GET', 'POST'])
def post():
    if request.method == "POST":
        code = request.form['code']
    else:
        code = "// Please type code here."
    print(f"Code: {repr(code)}")
    return render_template("index.html", code=code + " // Processed")


if __name__ == '__main__':
    app.run()
```

`templates/index.html`
```html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>code-input + Flask</title>

    <!--Prism-->
    <script src="https://cdn.jsdelivr.net/npm/prismjs@1.29.0/prism.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/prismjs@1.29.0/themes/prism.css"></link>

    <!--code-input-->
    <script src="https://cdn.jsdelivr.net/gh/WebCoder49/code-input@2.2/code-input.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/WebCoder49/code-input@2.2/code-input.min.css">

    <script>codeInput.registerTemplate("syntax-highlighted", codeInput.templates.prism(Prism, []))</script>
</head>
<body>
    <form method="POST">
        <code-input name="code" language="JavaScript">{{ code }}</code-input>
        <input type="submit"/>
    </form>
</body>
</html>
```

**Comment by george-gca** [comment]
My mistake, I just found out what the issue was. I was using [flask minify](https://github.com/mrf345/flask_minify/) in my application, and this is what was causing the issue. After commenting my `Minify(app=app, html=True, js=True, cssless=True)` it worked correctly.

Just for reference, my setup is:

| Package    | Version |
| -------    | ------- |
| Python | 3.11.6 |
| Flask | 3.0.2 |
| code-input | 2.2.1 |
| prism | 1.29.0 |
