### ISSUE TITLE
Provide documentation and examples for how to install and use with non-npm normal html and vanilla systems.

### ISSUE THREAD

**Issue by WhyFenceCode** [WebCoder49/code-input#90]
When i tried to do what you did in your tutorial it did not work. The code did not highlight, there was no way to make a new line. I therefore want to switch to using this, but I am unsure of 2 things:
1. Can i use hljs (highlight js) and if so how can i use a custom theme and use a downloaded version.
2. How do i use this in a normal webpage?

Any tutorials and/or answers are much appreciated.

**Comment by WebCoder49** [comment]
@WhyFenceCode Thank you for reaching out here! I have put together a demo HTML file [on CodePen here](https://codepen.io/WebCoder49/pen/vYMpMoJ?editors=1000). I should probably do the same for Prism.js and put them in the README, so please leave this issue open, but do let me know if this helps.

**Comment by WhyFenceCode** [comment]
Thank you so much, that helps a lot. You have just solved so many problems with a code editor I am writing. Do you want to be credited when I release @WebCoder49 ?

**Comment by WhyFenceCode** [comment]
Also, I am unable to make it scale to 100% width without overflow, and I can not remove margins/padding

**Comment by WebCoder49** [comment]
> Thank you so much, that helps a lot. You have just solved so many problems with a code editor I am writing. Do you want to be credited when I release @WebCoder49 ?
> 

Yes please, that would be nice! 😊 If it is OK, please could you credit me as the maintainer of code-input but also provide a link to https://github.com/webCoder49/code-input/graphs/contributors?

**Comment by WhyFenceCode** [comment]
Thank you so much, just an idea to fix this, make sure that your style sheet runs first, so that the others will override it. I might pr this when I have time

**Comment by WhyFenceCode** [comment]
Also, how do i download the files, and are all of them needed as I dont have npm or any package manager for my editor.

**Comment by WebCoder49** [comment]
> Also, how do i download the files, and are all of them needed as I dont have npm or any package manager for my editor.

You can download a ZIP file under the green `Code` button on the [main repository page](https://GitHub.com/WebCoder49/code-input), and extract its contents. I'd suggest keeping the README, JSON and d.ts files there as they will make it easier to remember where you got the code-input package from, work out its version number if you report later bugs, and give you a better editing experience. The code-input LICENSE file must be left and distributed with your software, as a legal requirement.

Out of the other files, having both .min.js and .js, .min.css and .css versions are useful as .min should be used in production and non-minified in testing. However, you can delete the `tests` and `.github` folders, and delete any plugins in the `plugins` folder you are not using. This will help make your repository smaller in size, but is not necessary.

This won't activate NPM or anything, as you are downloading the files from GitHub, not NPM (which is an alternative). I hope this clarifies things!

**Comment by WhyFenceCode** [comment]
Thank You For ALL YOUR HELP

**Comment by WhyFenceCode** [comment]
One last thing, when I use this it scales in an odd way (the entire page moves left) any ideas why? Using both width and height mess it up. Ill post my code:
https://github.com/WhyFenceCode/verbatim_code_editor
The styles applied are in editor.css

**Comment by WhyFenceCode** [comment]
fixed everything, thank you so much for all your help, im gonna close this and open one to remind you about docs
