### ISSUE TITLE
recommended get and set for data?

### ISSUE THREAD

**Issue by WhyFenceCode** [WebCoder49/code-input#94]
This is actually 2 qs:
1. Is there a recommended way to set/change the highlight language other than just set attribute?
2. Is there a recommended way to get and set the content, preferably one that de-sanitises /sanitises based on direction?

**Comment by WebCoder49** [comment]
1. To change the highlight language you should use (code-input element)`.setAttribute("language", newLanguage);`.
2. To get/set the content you should use (code-input element)`.value`. This should auto-escape/unescape the code in the preview `<pre><code>` element but doesn't sanitise in any other way.
Please let me know if you have any other questions / suggestions.
