### ISSUE TITLE
line numbers disappearing when text exceeds available space horizontally

### ISSUE THREAD

**Issue by SimonFliegel** [WebCoder49/code-input#95]
When the text exceeds the available space horizontally while line numbers are enabled (using prism-line-numbers-plugin) a scrollbar appears for horizontal scrolling as intended. However when scrolling all the way back to the left border the line numbers have disappeared and there is just the border which separates line numbers from code (see picture below). Please let me know when you have trouble reproducing the error.
Regards.

![Screenshot from 2024-04-19 18-09-47](https://github.com/WebCoder49/code-input/assets/101973895/d0897f42-718d-4e83-8ae1-1e646dc9ff0e)

**Comment by WebCoder49** [comment]
Thank you for pointing this out, @SimonFliegel. I am quite busy now but this definitely is near the top of priorities for code-input, and I will let you know when I start working on it.

**Comment by WebCoder49** [comment]
@SimonFliegel It seems like you might be using version 2.1.0 which does have this error; please could you [upgrade to the latest release 2.2](https://github.com/WebCoder49/code-input/releases/) (if you have problems, the upgrading guidance in the dropdown at the link might be useful). I should be releasing version 2.2.2 today/tomorrow so please wait for it if you want even more bug fixes in your version!

Please let me know if the bugs persist / other new ones appear.

**Comment by WebCoder49** [comment]
I will close this issue now but you can reopen it if you have any more questions.

**Comment by WebCoder49** [comment]
Sorry for the delay - I started to overhaul the docs and demos before the release, which I probably should have done afterwards! 🫢 I'm pretty sure I will release version 2.3 today, with this fix in it.
